# Generated by Django 2.2.12 on 2020-06-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_chile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['region', 'name'], 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['region', 'name'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code'], 'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
    ]
